spring:
  profiles:
    active: dev
  application:
    name: REVIRAL
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 20
        page-parameter: page
        size-parameter: size
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    username: reviralcompany@gmail.com
    password: pfugdgbrtbdepssx
    properties:
      debug: true
      smtp.ssl.enable: true
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 5MB
      max-request-size: 10MB
## AWS S3
cloud:
  aws:
    s3:
      bucket: reviral
    credentials:
      access-key: AKIAZPPF77WAX7CPGPUG
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  config: classpath:log/logger-${spring.profiles.active}.xml
