server:
  port: 9093

spring:
  profiles:
    active: dev
  application:
    name: Reviral
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 20
        page-parameter: page
        size-parameter: size

logging:
  config: classpath:log/logger-${spring.profiles.active}.xml
