server:
  port: 9093

spring:
  application:
    name: Reviral
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reviral
    username: root
    password: rlgus585
    hikari:
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      idle-timeout: 30000
      minimum-idle: 2
      connection-timeout: 10000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

